export const pricingPlans = [
  {
    id: 'starter',
    name: 'Starter',
    summary: 'For founders validating billing motion without spreadsheet drift.',
    monthly: 29,
    cta: 'Start lean',
    tone: 'Quiet launch plan',
    features: [
      { label: 'Revenue command center', included: true },
      { label: 'Monthly plan experiments', included: true },
      { label: 'Up to 3 teammate seats', included: true },
      { label: 'Basic usage alerts', included: true },
      { label: 'Self-serve invoice history', included: true },
      { label: 'Forecast snapshots', included: false },
      { label: 'Approval workflows', included: false },
      { label: 'Dedicated success desk', included: false },
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    summary: 'For growing teams that need clean pricing experiments and forecasting.',
    monthly: 79,
    cta: 'Choose Pro',
    tone: 'Most teams land here',
    featured: true,
    features: [
      { label: 'Revenue command center', included: true },
      { label: 'Monthly and annual experiments', included: true },
      { label: 'Up to 20 teammate seats', included: true },
      { label: 'Smart usage alerts', included: true },
      { label: 'Self-serve invoice history', included: true },
      { label: 'Forecast snapshots', included: true },
      { label: 'Approval workflows', included: true },
      { label: 'Dedicated success desk', included: false },
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    summary: 'For revenue organizations with controls, security, and rollout needs.',
    monthly: 249,
    cta: 'Talk to sales',
    tone: 'Scale without guesswork',
    features: [
      { label: 'Revenue command center', included: true },
      { label: 'Global price-book experiments', included: true },
      { label: 'Unlimited teammate seats', included: true },
      { label: 'Predictive usage alerts', included: true },
      { label: 'Advanced invoice archive', included: true },
      { label: 'Forecast snapshots', included: true },
      { label: 'Approval workflows', included: true },
      { label: 'Dedicated success desk', included: true },
    ],
  },
]
